//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.v1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.CampoClinicoAlumno = new HashSet<CampoClinicoAlumno>();
        }
    
        public int AlumnoId { get; set; }
        [DisplayName("Curso")]
        public string CursoNivel { get; set; }
        public string Observaciones { get; set; }
        public int PersonaPersonaId { get; set; }
        public int InmunizacionInmunizacionId { get; set; }
        public int CentroFormadorCentroFormadorId { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Inmunizacion Inmunizacion { get; set; }
        public virtual CentroFormador CentroFormador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampoClinicoAlumno> CampoClinicoAlumno { get; set; }
    }
}
