//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignaturaAlumno
    {
        public int Id { get; set; }
        public int AlumnoAlumnoId { get; set; }
        public int AsignaturaId { get; set; }
        public int AnioId { get; set; }
        public int SemestreId { get; set; }
        public EstadoAsignatura EstadoAsignatura { get; set; }
        public string AsignaturaPreRequisito { get; set; }
        public int PorcentajeDeExigenciaId { get; set; }
        public int CarreraCarreraId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Asignatura Asignatura { get; set; }
        public virtual Anio Anio { get; set; }
        public virtual Semestre Semestre { get; set; }
        public virtual PorcentajeDeExigencia PorcentajeDeExigencia { get; set; }
        public virtual Carrera Carrera { get; set; }
    }
}
