//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.v1.Models
{
    using System;
    
    public enum EstadoAsignatura : int
    {
        Aprobado = 1,
        AprobadoEnSegunda = 2,
        AprobadoEnTercera = 3,
        AprobadoEnCuarta = 4,
        Cursando = 5,
        CursandoEnSegunda = 6,
        CursandoEnTercera = 7,
        CursandoEnCuarta = 8,
        ReprobadoYNoInscrito = 9,
        ReprobadoYNoInscritoSegunda = 10,
        ReprobadoYNoInscritoTercera = 11,
        NoCursado = 12
    }
}
