//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.v1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Periodo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Periodo()
        {
            this.CampoClinicoAlumno = new HashSet<CampoClinicoAlumno>();
        }
    
        public int PeriodoId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaTermino { get; set; }
        public int NombreJornadaNombreJornadaId { get; set; }
    
        public virtual NombreJornada NombreJornada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampoClinicoAlumno> CampoClinicoAlumno { get; set; }

        [DisplayName("Fecha Inicio")]
        public virtual string FInicio
        {
            get
            {
                return string.Format("{0}", this.FechaInicio.ToShortDateString());
            }
        }
        [DisplayName("Fecha Termino")]
        public virtual string FTermino
        {
            get
            {
                return string.Format("{0}", this.FechaTermino.ToShortDateString());
            }
        }
        [DisplayName("Desde-Hasta")]
        public virtual string DesdeHasta
        {
            get
            {
                return string.Format("{0}/{1}", this.FechaInicio.ToShortDateString(), this.FechaTermino.ToShortDateString());
            }
        }
    }
}
