//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanEstudioAlumno
    {
        public int Id { get; set; }
        public int PlanDeEstudioId { get; set; }
        public int AlumnoAlumnoId { get; set; }
        public EstadoAsignatura EstadoAsignatura { get; set; }
    
        public virtual PlanDeEstudio PlanDeEstudio { get; set; }
        public virtual Alumno Alumno { get; set; }
    }
}
