//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanDeEstudio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanDeEstudio()
        {
            this.PlanEstudioAlumno = new HashSet<PlanEstudioAlumno>();
        }
    
        public int Id { get; set; }
        public int RequisitosAsignaturaId { get; set; }
        public int CarreraCarreraId { get; set; }
        public int AnioId { get; set; }
        public string UD { get; set; }
        public string Catedra { get; set; }
        public string Taller { get; set; }
        public string LAB { get; set; }
        public string PC { get; set; }
        public string SCT { get; set; }
        public string Materia { get; set; }
        public string Curso { get; set; }
    
        public virtual RequisitosAsignatura RequisitosAsignatura { get; set; }
        public virtual Carrera Carrera { get; set; }
        public virtual Anio Anio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanEstudioAlumno> PlanEstudioAlumno { get; set; }
    }
}
