//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitosAsignatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequisitosAsignatura()
        {
            this.PlanDeEstudio = new HashSet<PlanDeEstudio>();
        }
    
        public int Id { get; set; }
        public int AsignaturaId { get; set; }
        public string PorcentajeReprobacion { get; set; }
        public string AsignaturaPreRequisito { get; set; }
        public int SemestreId { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Semestre Semestre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanDeEstudio> PlanDeEstudio { get; set; }
    }
}
