//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudDeCupo
    {
        public int Id { get; set; }
        public int CarreraCarreraId { get; set; }
        public int CampoClinicoId { get; set; }
        public int ServicioId { get; set; }
        public int CuposAlumnos { get; set; }
        public int TotalSemanaPorGrupo { get; set; }
        public int PeriodoPeriodoId { get; set; }
        public int SupervisionId { get; set; }
        public int AsignaturaId { get; set; }
        public string Observacion { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual CampoClinico CampoClinico { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Supervision Supervision { get; set; }
        public virtual Asignatura Asignatura { get; set; }
    }
}
