//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string Cuenta { get; set; }
        public string Password { get; set; }
        public string Correo { get; set; }
        public string Estado { get; set; }
        public int PersonaPersonaId { get; set; }
        public int PerfilUsuarioId { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual PerfilUsuario PerfilUsuario { get; set; }
    }
}
